name: Ejecutar script Python cada 2 horas

on:
  schedule:
    - cron: '0 12,15,18,21,0,2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      env: # Or as an environment variable
        SHEETS_SERVICE_ACCOUNT: ${{ secrets.SHEETS_SERVICE_ACCOUNT }}
        REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}
        SHEET_NAME: ${{ vars.SHEET_NAME }}
        RANGE_NAME: ${{ vars.RANGE_NAME }}
        CREDENTIALS_FILE: ${{ vars.CREDENTIALS_FILE }}
        FILE_NAME: ${{ vars.FILE_NAME }}
        REPO_PATH: ${{ vars.REPO_PATH }}
        REPO_BRANCH: ${{ vars.REPO_BRANCH }}
        REPO_FILE_PATH: ${{ vars.REPO_FILE_PATH }}
      run: python replace_from_sheets.py
